config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing'

  resources :skus
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #root 'application#hello'
end

app/models/sku.rb
class Sku
  include Mongoid::Document
  include Mongoid::Timestamps
  field :skuid, type: Integer
  field :skuname, type: String
  field :avgsaleprice, type: BigDecimal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  def hello
    render text: "Hello World"
  end
end

app/controllers/skus_controller.rb
class SkusController < ApplicationController
  before_action :set_sku, only: [:show, :edit, :update, :destroy]

  # GET /skus
  # GET /skus.json
  def index
    @skus = Sku.all
  end

  # GET /skus/1
  # GET /skus/1.json
  def show
  end

  # GET /skus/new
  def new
    @sku = Sku.new
  end

  # GET /skus/1/edit
  def edit
  end

  # POST /skus
  # POST /skus.json
  def create
    @sku = Sku.new(sku_params)

    respond_to do |format|
      if @sku.save
        format.html { redirect_to @sku, notice: 'Sku was successfully created.' }
        format.json { render :show, status: :created, location: @sku }
      else
        format.html { render :new }
        format.json { render json: @sku.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skus/1
  # PATCH/PUT /skus/1.json
  def update
    respond_to do |format|
      if @sku.update(sku_params)
        format.html { redirect_to @sku, notice: 'Sku was successfully updated.' }
        format.json { render :show, status: :ok, location: @sku }
      else
        format.html { render :edit }
        format.json { render json: @sku.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skus/1
  # DELETE /skus/1.json
  def destroy
    @sku.destroy
    respond_to do |format|
      format.html { redirect_to skus_url, notice: 'Sku was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sku
      @sku = Sku.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sku_params
      params.require(:sku).permit(:skuid, :skuname, :avgsaleprice)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/skus_helper.rb
module SkusHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Item Profitability Engine</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-light navbar-fixed-top bg-faded">
        <div class="container">
          <a class="navbar-brand" href="#">e-Sight</a>
        </div><!-- end navbar container -->  
      </nav>
    
    <%= yield %>
    </div><!-- end main container --> 
  </body>
</html>

app/views/skus/_form.html.erb
<%= form_for(sku) do |f| %>
  <% if sku.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sku.errors.count, "error") %> prohibited this sku from being saved:</h2>

      <ul>
      <% sku.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :skuid %>
    <%= f.number_field :skuid %>
  </div>

  <div class="field">
    <%= f.label :skuname %>
    <%= f.text_field :skuname %>
  </div>

  <div class="field">
    <%= f.label :avgsaleprice %>
    <%= f.text_field :avgsaleprice %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skus/edit.html.erb
<h1>Editing Sku</h1>

<%= render 'form', sku: @sku %>

<%= link_to 'Show', @sku %> |
<%= link_to 'Back', skus_path %>

app/views/skus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Skus</h1>

<table>
  <thead>
    <tr>
      <th>Skuid</th>
      <th>Skuname</th>
      <th>Avgsaleprice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @skus.each do |sku| %>
      <tr>
        <td><%= sku.skuid %></td>
        <td><%= sku.skuname %></td>
        <td><%= sku.avgsaleprice %></td>
        <td><%= link_to 'Show', sku %></td>
        <td><%= link_to 'Edit', edit_sku_path(sku) %></td>
        <td><%= link_to 'Destroy', sku, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sku', new_sku_path %>

app/views/skus/new.html.erb
<h1>New Sku</h1>

<%= render 'form', sku: @sku %>

<%= link_to 'Back', skus_path %>

app/views/skus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Skuid:</strong>
  <%= @sku.skuid %>
</p>

<p>
  <strong>Skuname:</strong>
  <%= @sku.skuname %>
</p>

<p>
  <strong>Avgsaleprice:</strong>
  <%= @sku.avgsaleprice %>
</p>

<%= link_to 'Edit', edit_sku_path(@sku) %> |
<%= link_to 'Back', skus_path %>

app/views/static_pages/landing.html.erb
</div><!-- end main container from application.html.erb -->

  <section class="page-header">
    <h1 class="project-name">e-Sight</h1><br>
    <h2 class="project-tagline">Item Profitability Engine for e-commerce platforms</h2>
    
    <a href="/skus" class="btn">Get Started</a>
   
    
    <div style="margin-top:100px"><!-- Typing Animation -->
      <span class="element"></span>
    </div>
    
  </section>
  
  <script>
  $(function(){
      $(".element").typed({
        strings: [
          "Find out shipping profitability of Online assortment.", 
          "Decide correct multiples for Online SKUs to maximize margins.",
          "Cloud based plug and play webservice for existing e-commerce platforms."
          ],
        typeSpeed: 20
      });
  });
  </script>

<div class="container"><!-- Restart the main container from application.html.erb -->